import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CustomNavbar from "@/component/CustomNavbar";
import Footer from "@/component/Footer";
import { ToastContainer } from "react-toastify";
import UserProvider from "./context/userProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
        <CustomNavbar />
          <ToastContainer />
          <div className="mt-2"> {children} </div>
          <Footer />
        </UserProvider>
      </body>
    </html>
  );
}
